// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.2
// source: managment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MembershipChange_EventType int32

const (
	MembershipChange_ADDED    MembershipChange_EventType = 0
	MembershipChange_LOST     MembershipChange_EventType = 1
	MembershipChange_REJOINED MembershipChange_EventType = 2
	MembershipChange_LEFT     MembershipChange_EventType = 3
)

// Enum value maps for MembershipChange_EventType.
var (
	MembershipChange_EventType_name = map[int32]string{
		0: "ADDED",
		1: "LOST",
		2: "REJOINED",
		3: "LEFT",
	}
	MembershipChange_EventType_value = map[string]int32{
		"ADDED":    0,
		"LOST":     1,
		"REJOINED": 2,
		"LEFT":     3,
	}
)

func (x MembershipChange_EventType) Enum() *MembershipChange_EventType {
	p := new(MembershipChange_EventType)
	*p = x
	return p
}

func (x MembershipChange_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MembershipChange_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_managment_proto_enumTypes[0].Descriptor()
}

func (MembershipChange_EventType) Type() protoreflect.EnumType {
	return &file_managment_proto_enumTypes[0]
}

func (x MembershipChange_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MembershipChange_EventType.Descriptor instead.
func (MembershipChange_EventType) EnumDescriptor() ([]byte, []int) {
	return file_managment_proto_rawDescGZIP(), []int{0, 0}
}

// MembershipChange is an event;  it should have more metadata (see stuff.proto for that discussion)
// this is more 'here is an idea'
type MembershipChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType MembershipChange_EventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=proto.MembershipChange_EventType" json:"event_type,omitempty"`
	Member    *Member                    `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *MembershipChange) Reset() {
	*x = MembershipChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_managment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MembershipChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipChange) ProtoMessage() {}

func (x *MembershipChange) ProtoReflect() protoreflect.Message {
	mi := &file_managment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipChange.ProtoReflect.Descriptor instead.
func (*MembershipChange) Descriptor() ([]byte, []int) {
	return file_managment_proto_rawDescGZIP(), []int{0}
}

func (x *MembershipChange) GetEventType() MembershipChange_EventType {
	if x != nil {
		return x.EventType
	}
	return MembershipChange_ADDED
}

func (x *MembershipChange) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

// Membership is just  a list of members
type Membership struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Memberlist []*Member `protobuf:"bytes,1,rep,name=memberlist,proto3" json:"memberlist,omitempty"`
}

func (x *Membership) Reset() {
	*x = Membership{}
	if protoimpl.UnsafeEnabled {
		mi := &file_managment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_managment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_managment_proto_rawDescGZIP(), []int{1}
}

func (x *Membership) GetMemberlist() []*Member {
	if x != nil {
		return x.Memberlist
	}
	return nil
}

type Member struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Port    string `protobuf:"bytes,3,opt,name=Port,proto3" json:"Port,omitempty"`
}

func (x *Member) Reset() {
	*x = Member{}
	if protoimpl.UnsafeEnabled {
		mi := &file_managment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_managment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_managment_proto_rawDescGZIP(), []int{2}
}

func (x *Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Member) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Member) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

var File_managment_proto protoreflect.FileDescriptor

var file_managment_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb5, 0x01, 0x0a, 0x10, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x68, 0x69, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x40, 0x0a, 0x0a, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69,
	0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x06,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0x38, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x09, 0x0a, 0x05, 0x41, 0x44, 0x44, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4c,
	0x4f, 0x53, 0x54, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x4a, 0x4f, 0x49, 0x4e, 0x45,
	0x44, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x03, 0x22, 0x3b, 0x0a,
	0x0a, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x2d, 0x0a, 0x0a, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x0a,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x4a, 0x0a, 0x06, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x32, 0x99, 0x01, 0x0a, 0x10, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x48, 0x0a, 0x11, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3b, 0x0a, 0x0e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x68, 0x69, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68,
	0x69, 0x70, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x79, 0x61, 0x72, 0x62, 0x65, 0x6c, 0x6b, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x73, 0x74, 0x75,
	0x66, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_managment_proto_rawDescOnce sync.Once
	file_managment_proto_rawDescData = file_managment_proto_rawDesc
)

func file_managment_proto_rawDescGZIP() []byte {
	file_managment_proto_rawDescOnce.Do(func() {
		file_managment_proto_rawDescData = protoimpl.X.CompressGZIP(file_managment_proto_rawDescData)
	})
	return file_managment_proto_rawDescData
}

var file_managment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_managment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_managment_proto_goTypes = []interface{}{
	(MembershipChange_EventType)(0), // 0: proto.MembershipChange.EventType
	(*MembershipChange)(nil),        // 1: proto.MembershipChange
	(*Membership)(nil),              // 2: proto.Membership
	(*Member)(nil),                  // 3: proto.Member
	(*emptypb.Empty)(nil),           // 4: google.protobuf.Empty
}
var file_managment_proto_depIdxs = []int32{
	0, // 0: proto.MembershipChange.event_type:type_name -> proto.MembershipChange.EventType
	3, // 1: proto.MembershipChange.member:type_name -> proto.Member
	3, // 2: proto.Membership.memberlist:type_name -> proto.Member
	4, // 3: proto.ClusterManagment.MembershipChanges:input_type -> google.protobuf.Empty
	4, // 4: proto.ClusterManagment.MembershipList:input_type -> google.protobuf.Empty
	1, // 5: proto.ClusterManagment.MembershipChanges:output_type -> proto.MembershipChange
	2, // 6: proto.ClusterManagment.MembershipList:output_type -> proto.Membership
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_managment_proto_init() }
func file_managment_proto_init() {
	if File_managment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_managment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MembershipChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_managment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Membership); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_managment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Member); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_managment_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_managment_proto_goTypes,
		DependencyIndexes: file_managment_proto_depIdxs,
		EnumInfos:         file_managment_proto_enumTypes,
		MessageInfos:      file_managment_proto_msgTypes,
	}.Build()
	File_managment_proto = out.File
	file_managment_proto_rawDesc = nil
	file_managment_proto_goTypes = nil
	file_managment_proto_depIdxs = nil
}
